project:
  type: website
  output-dir: .
  render:
    - index.qmd
    - projects.qmd
    - blog.qmd
    - notes.qmd
    - projects/
    - posts/
    - notes/

website:
  title: "Ramana Botta"
  description: "Personal website of Ramana Botta"
  site-url: "https://ramanrobotics.github.io"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: blog.qmd
        text: Blog
      - href: notes.qmd
        text: Notes
    right:
      - icon: envelope
        href: mailto:chandhra1999@gmail.com
        aria-label: Email
      - icon: linkedin
        href: https://www.linkedin.com/in/ramanabotta
        aria-label: LinkedIn
      - icon: github
        href: https://github.com/RamanaBotta
        aria-label: GitHub
      - icon: twitter-x
        href: https://x.com/ramanabotta
        aria-label: X (Twitter)
  page-footer:
    center: "&copy; 2026 Ramana Botta"
    background: light

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    grid:
      body-width: 850px
